# Generated by Django 2.2.12 on 2020-07-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='test_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
