# Generated by Django 2.2.12 on 2020-08-04 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_studentmarks_test_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_by_teacher', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('message_html', models.TextField(editable=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='classroom.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='classroom.Teacher')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'teacher', 'message')},
            },
        ),
        migrations.DeleteModel(
            name='MessageToTeacher',
        ),
    ]
